version: '3.5'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: cssmod_todo
        ports:
            - '3000:3000'
        volumes:
            - .:/app
